= Transition

To me Transition with a capital T is about transitioning our world from a late 20th century mentality into a 23rd century society.

It's about moving from a world where your survival is not guaranteed, to a world where everything you need to survive is available to you without question. Where you can live in peace knowing that everything you need: food, clothes, shelter, energy and health care are provided.


== Something is Wrong 

There is something really wrong with the world when not everyone that wants a job can get a job. It is worse when the job you can get is not enough to pay for the essentials. 

I know what you are thinking; who's going to pay for everyone to have food, clothes, shelter, energy and health care? 

To start we will have to put *people before profits*. Which is going to turn most businesses into non-profit businesses.

This might be a scary thought for some, but let's explore it for a minute.

[quote]
____
What work would get done if no one was getting paid to do it? 
____

We would have to really boil it down to essentials.


== Transitioning to Peace

Imagine what it would feel like if you didn't have to worry about paying the rent or worry about having enough to eat tomorrow.

Once we eliminate the threat that you might die tomorrow, people can relax and live in harmony with their neighbors.

== Stay Tuned

If these concepts sound interesting, please stay tuned. I intend to discuss and imagine what it will take for all of us to Transition our world.

