= Get Paid for Every Contribution
test this

TIP: The use of money is the root of all evil.

We were born into a world that requires us to use money.

You and I can responsibly and morally use money correctly as a tool.

However lack of money is a giant limiter of abundance.

If we were truly using money correctly, then anytime anyone spends an hour contributing something to this world, they should be compensated for it.
Even if is just to share a smile, they should be compensated.

But who is going to pay for that?

And therein lies the problem with using money.
*Either we need to get paid for everything we contribute or we need to stop using money all together.*

If you spend a hour writing something entertaining and just one person gets something from it, even if it is just a laugh.
Then I assert that you contributed something of value to society.
That person that was entertained should be able to give it a thumbs up.
That thumbs up 'vote' should be submitted to the 'community bank' and you should be given compensation for 1 hour's worth of work.

Since everyone's contribution should be valued equally, a deposit of $21.72 should go into your account.
(based on the average hourly wage in USA as of 2016 according to link:http://www.tradingeconomics.com/united-states/wages[Trading Economics])

Maybe evertime someone gives it a thumbs up, they should be compensated?

In reality we only get money when someone or some business is willing to pay us for our work.
We are very limited in contributing anything outside of 'the job'.
We must prioritize our contributions, doing things for money first, before doing anything else.

One of the biggest problems with using money is it forces us to choose to do something to get money to survive.
Often in despiration people end up chosing to do something to get money even if in goes against their better moral judgement.
Most people have never been this desperate, but when it comes done to survival, they will choose the work over starving, or losing their house, or car, or whatever they value in this world.

One solution is link:https://www.ubuntuplanet.org/[Ubuntu contributionism] where everyone contributes few hours a week.
To make sure every man, woman and child has food, clothes, shelter, electricity and healthcare.

That is the only 'job' people have.
You contribute three hours a week helping to grow food, make clothes, generate electricty, repair houses, etc.
Then when you need food, you just go to the warehouse and get it.
You need a house, the community builds one. 

____
icon:question-circle[3x, role=yellow] Would you be willing to trade your 40 hour a week job for a 3 hour a week job?
____

Once everyone has the basics to survive, the rest of the time we can do what we want with our lives.
Imagine the new utopia we would create when everyone has peace knowing they have a place to live and food to eat.
Most problems will fall away.


